# Generated by Django 3.2.9 on 2022-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
