# Generated by Django 5.0.7 on 2024-07-12 15:55

import common.utils
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_alter_contact_id_alter_post_id_alter_profile_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="picture",
        ),
        migrations.AddField(
            model_name="comment",
            name="media",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    common.utils.file_upload, *("comments_media",), **{}
                ),
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    common.utils.file_upload, *("background_images",), **{}
                ),
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="network.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="network.post",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("Like", "Like Reaction"),
                    ("Love", "Love Reaction"),
                    ("Laugh", "Laught Reaction"),
                    ("Sad", "Sad Readction"),
                    ("Care", "Care Reaction"),
                    ("Angry", "Angry Reaction"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="default.png",
                upload_to=functools.partial(
                    common.utils.file_upload, *("users/%Y/%m/%d/",), **{}
                ),
            ),
        ),
        migrations.CreateModel(
            name="Retalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_post",
                        to="network.post",
                    ),
                ),
                (
                    "retalk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retalks",
                        to="network.retalk",
                    ),
                ),
                (
                    "retalked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
