# Generated by Django 5.0.7 on 2024-07-12 16:48

import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "network",
            "0003_remove_comment_picture_comment_media_post_is_private_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-published",)},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="body",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="post",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="post",
            name="users_like",
        ),
        migrations.RemoveField(
            model_name="postreaction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="postreaction",
            name="reaction",
        ),
        migrations.AddField(
            model_name="comment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="status", when={"published"}
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="type",
            field=model_utils.fields.StatusField(
                choices=[("post", "post"), ("video", "video")],
                default="post",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="type",
            field=model_utils.fields.StatusField(
                choices=[
                    ("Like", "Like"),
                    ("Love", "Love"),
                    ("Laugh", "Laugh"),
                    ("Sad", "Sad"),
                    ("Care", "Care"),
                    ("Angry", "Angry"),
                ],
                default="Like",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[("draft", "draft"), ("published", "published")],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
