# Generated by Django 5.0.7 on 2024-07-12 16:48

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="created_at",
        ),
        migrations.AddField(
            model_name="block",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
